src/InventoryTracker/Controllers/UsersController.cs
using InventoryTracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace InventoryTracker.Controllers
{
    public class UsersController : Controller
    {
        private DBContexts _context;

        public UsersController(DBContexts context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Users.ToList());
        }
        [Authorize(Policy = "Dickbuttz")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Dickbuttz")]
        public IActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {

                user.Password = CryptoHelper.Crypto.HashPassword(user.Password);
                _context.Users.Add(user);
                _context.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(user);
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View("Login");

        }
        [HttpPost]
        public async Task<IActionResult> Login(String username, String password)
        {
            var hashedPassList = from u in _context.Users where u.Username.Equals(username) select u;
            if (!hashedPassList.Any())
            {
                return View("Login");

            }
            User userRequested = hashedPassList.Last();
            List<Claim> claims = new List<Claim>
            {
                new Claim("Rick","Sanchez")
            };
            var id = new ClaimsIdentity(claims,"local","name","role");
            if (CryptoHelper.Crypto.VerifyHashedPassword(userRequested.Password, password))
            {

                ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(id);
                await HttpContext.Authentication.SignInAsync("MyCookieMiddlewareInstance", claimsPrincipal);
                return View("Create");
            }
            else
            {
                return View("Login");
            }
        }
        [Authorize(Policy = "Dickbuttz")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.Authentication.SignOutAsync("MyCookieMiddlewareInstance");
            return View("Login");
        }



    }
}

src/InventoryTracker/Views/Shared/Login.cshtml
@model InventoryTracker.Models.User
@{
    ViewData["Title"] = "Log In";
}

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <section>
            <form asp-controller="Users" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <h4>Log In</h4>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Username"></label>
                    <input asp-for="Username" class="form-control input-lg" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input type ="password" asp-for="Password" class="form-control input-lg" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Log in</button>
                </div>
            </form>
        </section>
    </div>
</div>

src/InventoryTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Inventory Tracker</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <nav>
        <div class="nav-wrapper teal make-bigger">
            <a href="#!" class="brand-logo center title-font">Inventory of Things</a>
            <ul class="left hide-on-med-and-down classes">
                <li><a href="/Users/Login">Login</a></li>
                <li class="active"><a href="/InventoryItems">Table</a></li>
            </ul>
            <form asp-controller="Users" asp-action="Logout" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <div class="form-group">
                    <p style="float:right;margin: 0,15px,0,0"><button type="submit" class="btn btn-success btn-lg btn-block">Log Out</button></p>
                </div>
            </form>
        </div>
    </nav>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FancyWebpage</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>*@
    <div class="backgroundimg">
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2017 - FancyWebpage</p>
            </footer>
        </div>
    </div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/materialize/js/materialize.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>